### ISSUE TITLE
When I

### ISSUE THREAD

**Issue by mkshift** [dollarkillerx/blackwater#1]

**Comment by mkshift** [comment]
Build as Apple darwin execute file ,  I can't scan anything.

**Comment by dollarkillerx** [comment]
## Parameter adjustment, solve the problem of packet loss
There are many reasons for packet loss, roughly divided into two. 
1. network problems (solution: 1. switch to a better network 2. modify the `-t` timeout time) 
2. cpu processing super link performance is insufficient (solution: reduce the number of concurrent)
- Extranet scan, not missing a port
    - Modify thread parameters `-c` Calculation formula: Number of current CPU logical cores * 100
    - Example: Current CPU logical core is 4 cores Parameter is `blackwater -i github.com -c 400 -p 1-65535 `
- Intranet scan, not missing a port
    - Modify thread parameters `-c` Calculation formula: Number of current CPU logical cores * 250
    - Example: Current CPU logical core is 4 cores Parameter is `blackwater -i 192.168.88.11 -c 1000 -p 1-65535 `
