### ISSUE TITLE
port scan may miss

### ISSUE THREAD

**Issue by starnightcyber** [dollarkillerx/blackwater#4]
hi @dollarkillerx,
I use another very quick port scanner rustscan, which is written in rust, too.
You  can see from the following picture, that blackwater miss 9418 port open for github.com
![image](https://user-images.githubusercontent.com/19260696/125551474-1c5e2d62-c3fe-4991-bd70-66303b8afce2.png)

And blackwater is a very cool tool for port scanning.
If you can check why this port missing, i think it will make this tool better.

**Comment by dollarkillerx** [comment]
` blackwater -h`   view the default scan port

Note When a large scale scan is performed, pay attention to set timeout.
